set(_CATKIN_CURRENT_PACKAGE "qt_ros_test")
set(qt_ros_test_VERSION "0.0.0")
set(qt_ros_test_MAINTAINER "hans <hans@todo.todo>")
set(qt_ros_test_PACKAGE_FORMAT "1")
set(qt_ros_test_BUILD_DEPENDS "roscpp" "std_msgs")
set(qt_ros_test_BUILD_EXPORT_DEPENDS "roscpp" "std_msgs")
set(qt_ros_test_BUILDTOOL_DEPENDS "catkin")
set(qt_ros_test_BUILDTOOL_EXPORT_DEPENDS )
set(qt_ros_test_EXEC_DEPENDS "roscpp" "std_msgs")
set(qt_ros_test_RUN_DEPENDS "roscpp" "std_msgs")
set(qt_ros_test_TEST_DEPENDS )
set(qt_ros_test_DOC_DEPENDS )
set(qt_ros_test_URL_WEBSITE "")
set(qt_ros_test_URL_BUGTRACKER "")
set(qt_ros_test_URL_REPOSITORY "")
set(qt_ros_test_DEPRECATED "")